/**
 * Fallback models map when API calls fail
 */
export const FALLBACK_MODELS: Record<string, string[]> = {
  "BMW": ["3 SERIES", "5 SERIES", "7 SERIES", "X3", "X5", "X7", "M3", "M5", "M8"],
  "MERCEDES-BENZ": ["C-CLASS", "E-CLASS", "S-CLASS", "GLC", "GLE", "GLS", "AMG GT", "G-CLASS"],
  "AUDI": ["A3", "A4", "A6", "A8", "Q3", "Q5", "Q7", "Q8", "R8", "TT"],
  "PORSCHE": ["911", "CAYENNE", "MACAN", "PANAMERA", "TAYCAN", "718 CAYMAN", "718 BOXSTER"],
  "LAND ROVER": ["RANGE ROVER", "RANGE ROVER SPORT", "RANGE ROVER EVOQUE", "DISCOVERY", "DEFENDER"],
  "MCLAREN": ["720S", "ARTURA", "GT", "SENNA", "P1", "F1"],
  "ROLLS-ROYCE": ["PHANTOM", "GHOST", "WRAITH", "DAWN", "CULLINAN"],
  "FERRARI": ["488", "F8", "SF90", "ROMA", "PORTOFINO", "LAFERRARI"],
  "LAMBORGHINI": ["HURACAN", "AVENTADOR", "URUS", "REVUELTO"],
  "BENTLEY": ["CONTINENTAL", "FLYING SPUR", "BENTAYGA", "MULSANNE"],
  "ASTON MARTIN": ["DB11", "VANTAGE", "DBS", "DBX", "VALKYRIE"],
  "TOYOTA": ["CAMRY", "COROLLA", "RAV4", "HIGHLANDER", "PRIUS", "SUPRA", "LAND CRUISER"],
  "HONDA": ["CIVIC", "ACCORD", "CR-V", "PILOT", "PASSPORT", "RIDGELINE", "NSX"],
  "FORD": ["F-150", "MUSTANG", "EXPLORER", "ESCAPE", "EDGE", "EXPEDITION", "BRONCO"],
  "CHEVROLET": ["SILVERADO", "CAMARO", "CORVETTE", "EQUINOX", "TRAVERSE", "TAHOE", "SUBURBAN"],
  "NISSAN": ["ALTIMA", "SENTRA", "ROGUE", "MURANO", "PATHFINDER", "ARMADA", "GT-R"],
  "LEXUS": ["ES", "IS", "GS", "LS", "RX", "GX", "LX", "LC", "RC"],
  "INFINITI": ["Q50", "Q60", "QX50", "QX60", "QX80"],
  "ACURA": ["ILX", "TLX", "RLX", "RDX", "MDX", "NSX"],
  "GENESIS": ["G70", "G80", "G90", "GV70", "GV80"],
  "VOLVO": ["S60", "S90", "XC40", "XC60", "XC90"],
  "VOLKSWAGEN": ["JETTA", "PASSAT", "ATLAS", "TIGUAN", "ARTEON", "GOLF", "BEETLE"],
  "SUBARU": ["IMPREZA", "LEGACY", "OUTBACK", "FORESTER", "ASCENT", "WRX", "BRZ"],
  "MAZDA": ["MAZDA3", "MAZDA6", "CX-3", "CX-5", "CX-9", "MX-5 MIATA"],
  "KIA": ["FORTE", "OPTIMA", "SORENTO", "SPORTAGE", "TELLURIDE", "STINGER"],
  "HYUNDAI": ["ELANTRA", "SONATA", "SANTA FE", "TUCSON", "PALISADE", "VELOSTER"],
  "JEEP": ["WRANGLER", "GRAND CHEROKEE", "CHEROKEE", "COMPASS", "RENEGADE", "GLADIATOR"],
  "RAM": ["1500", "2500", "3500", "PROMASTER"],
  "GMC": ["SIERRA", "YUKON", "ACADIA", "TERRAIN", "CANYON"],
  "LINCOLN": ["CONTINENTAL", "MKZ", "NAVIGATOR", "AVIATOR", "CORSAIR"],
  "CADILLAC": ["ATS", "CTS", "XTS", "ESCALADE", "XT4", "XT5", "XT6"],
  "BUICK": ["ENCORE", "ENVISION", "LACROSSE", "REGAL"],
  "CHRYSLER": ["300", "PACIFICA", "VOYAGER"],
  "DODGE": ["CHARGER", "CHALLENGER", "DURANGO", "JOURNEY", "GRAND CARAVAN"],
  "ALFA ROMEO": ["GIULIA", "STELVIO", "4C"],
  "MASERATI": ["GHIBLI", "QUATTROPORTE", "LEVANTE", "MC20"],
  "BUGATTI": ["CHIRON", "VEYRON", "DIVO"],
  "KOENIGSEGG": ["REGERA", "AGERA", "JESKO", "GEMERA"],
  "PAGANI": ["HUAYRA", "ZONDA", "UTOPIA"],
  "RIVIAN": ["R1T", "R1S"],
  "TESLA": ["MODEL S", "MODEL 3", "MODEL X", "MODEL Y", "CYBERTRUCK", "ROADSTER"],
  "LUCID": ["AIR", "GRAVITY"],
  "POLESTAR": ["POLESTAR 2", "POLESTAR 3", "POLESTAR 4"]
};

export function getFallbackModels(make: string): string[] {
  return FALLBACK_MODELS[make.toUpperCase()] || [];
}
